services:
  dbbackup:
    image: ghcr.io/romkey/hackstack-db-backup:latest
    hostname: dbbackup
    container_name: dbbackup
    restart: unless-stopped
    user: "${BACKUP_UID:-0}:${BACKUP_GID:-0}"
    volumes:
      - /opt:/opt:ro
      - backup_nfs:/dest
    networks:
      - backup-net
    env_file:
      - .env

volumes:
  backup_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},${NFS_OPTIONS:-nfsvers=4,soft,rw}
      device: ":${NFS_PATH}"

networks:
  backup-net:
    name: dbbackup-net
