services:
  dbbackup:
    build: .
    hostname: dbbackup
    container_name: dbbackup
    restart: unless-stopped
    volumes:
      - ./app:/app
      - /opt:/opt:ro
      - backup_nfs:/dest
    networks:
      postgres: null
      mariadb: null
      redis: null
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    env_file:
      - .env

volumes:
  backup_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},${NFS_OPTIONS:-nfsvers=4,soft,rw}
      device: ":${NFS_PATH}"

networks:
  postgres:
    external: true
    name: postgres-net
  mariadb:
    external: true
    name: mariadb-net
  redis:
    external: true
    name: redis-net
